name: flutter_camera_ml_vision
description: A flutter widget that show the camera stream and allow ML vision recognition on it, it allow you to detect barcodes, labels, text, faces...
version: 3.0.1
repository: https://github.com/rushio-consulting/flutter_camera_ml_vision
homepage: https://github.com/rushio-consulting/flutter_camera_ml_vision
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # google_ml_vision:
  #   git:
  #     url: https://github.com/CoryADavis/flutter_google_ml_vision.git
  #     ref: barcode-only
  google_mlkit_commons: ^0.6.0
  path_provider: ^2.1.1
  pedantic: ^1.11.1
  camera: 0.10.5+5
  camera_android_camerax: 0.5.0+22
  collection:

dev_dependencies:
  flutter_test:
    sdk: flutter
