name: flutter_camera_ml_vision
description: A flutter widget that show the camera stream and allow ML vision recognition on it, it allow you to detect barcodes, labels, text, faces...
version: 3.0.1
repository: https://github.com/rushio-consulting/flutter_camera_ml_vision
homepage: https://github.com/rushio-consulting/flutter_camera_ml_vision
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_ml_vision:
    git:
      url: https://github.com/CoryADavis/flutter_google_ml_vision.git
      ref: barcode-only
  firebase_core: ^1.14.0
  visibility_detector: ^0.2.2
  path_provider: ^2.0.9
  pedantic: ^1.11.1
  device_info: ^2.0.3
  camera: ^0.9.8+1
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
